# Generated by Django 4.2.10 on 2024-04-18 11:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_people', '0005_alter_parent_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermFees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_term', models.CharField(max_length=70, unique=True)),
                ('fees', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFeePaid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.FloatField()),
                ('balance', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_people.student')),
                ('termfees', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='term', to='finances.termfees')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_people.student')),
            ],
        ),
    ]
