# Generated by Django 4.2.10 on 2024-04-18 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_people', '0005_alter_parent_phone_number'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termfees',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='end of term date'),
        ),
        migrations.AddField(
            model_name='termfees',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_people.school'),
        ),
        migrations.AddField(
            model_name='termfees',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Start of term date'),
        ),
    ]
