# Generated by Django 4.2.10 on 2024-04-18 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_termfees_end_date_termfees_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termfees',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='end of term date'),
        ),
        migrations.AlterField(
            model_name='termfees',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start of term date'),
        ),
    ]
